blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import BlogHome, BlogPost, CategoryView, searchPost, emailSubscription, unsubscribeEmail, TagView, ContactMe

# app_name = 'blog'
urlpatterns = [
    path('', BlogHome, name='home'),
    path('ContactMe/', ContactMe, name='ContactMe'),
    path('blog/<slug:slug>/', BlogPost, name='single_post'),
    path('category/<slug:slug>/', CategoryView, name='Category'),
    path('tag/<slug:slug>/', TagView, name='Tag'),
    path('search/', searchPost, name='searchPost'),
    path('emailSubscription/', emailSubscription, name='emailSubscription'),
    path('unsubscribeEmail/<str:pk>',unsubscribeEmail,name='unsubscribeEmail'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

codeforces/urls.py
from django.urls import path 
from django.conf import settings
from django.conf.urls.static import static
from .views import formView, confirmMail, unSubscribeCF

app_name = 'codeforces'
urlpatterns = [
    path('form/', formView , name='cfForm'),
    path('confirmMail/<str:uid>', confirmMail , name='confirmMail'),
    path('unSubscribeCF/<str:uid>', unSubscribeCF , name='unSubscribeCF'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import re_path

from django.contrib import admin

admin.site.site_header = 'Moontasir Admin Dashboard'     # default: "Django Administration"
admin.site.index_title = 'Features area'                 # default: "Site administration"
admin.site.site_title = 'Moontasir'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('codeforces/', include('codeforces.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    re_path(r'^static/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT,
        }),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

codeforces/models.py
from django.db import models
import uuid

# Create your models here.

class Handle(models.Model):
    handle = models.CharField(max_length=250)
    firstName = models.CharField(max_length=250)
    lastName = models.CharField(max_length=250)
    email = models.EmailField(primary_key=True)
    isVerified = models.BooleanField(default=False)
    uid = models.CharField(max_length=250,null=True,blank=True)
    isActive = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.uid:
            self.uid = str(uuid.uuid4())[:249]
        return super().save(*args, **kwargs)
    
    def __str__(self):
        return self.email

class Contest(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255)
    date = models.DateTimeField()
    isSend = models.BooleanField(default=False)
    isParsed = models.BooleanField(default=False)
    tryCount = models.IntegerField(default=0)
    # number of Try, isSaved,


    class Meta:
        ordering = ['-date',]


class Rank(models.Model):
    handle = models.CharField(max_length=250)
    contest = models.ForeignKey(Contest, on_delete= models.CASCADE)
    globalRank = models.IntegerField(null=True, blank=True)
    country = models.CharField(max_length=100, null=True, blank=True)
    countryRank= models.IntegerField(null=True , blank=True)
    organization = models.CharField(max_length=250, null=True, blank=True)
    organizationRank= models.IntegerField(null=True, blank=True)

    def __str__(self):
        return str(self.id)
    
    class Meta:
        ordering = ['-contest', 'globalRank']

codeforces/views.py
from django.shortcuts import render 
from django.http import JsonResponse
from django.core.validators import validate_email
from blog.views import SideBarWork
from .models import Handle
from django.contrib import messages
import os
from codeforces.helper import send_mass_html_mail
# Create your views here.

def formView(request):
    context ={}

    if request.is_ajax():
        first_name = request.POST.get('first_name', None)
        last_name = request.POST.get('last_name', None)
        codeforces_handle = request.POST.get('codeforces_handle', None)
        email_address = request.POST.get('email_address', None)

        try :
            validate_email(email_address)
            assert(len(first_name)>0)
            assert(len(last_name)>0)
            assert(len(codeforces_handle)>0)
            # print(first_name,last_name,email_address,codeforces_handle)


            obj = Handle(firstName = first_name,lastName=last_name,email = email_address,handle = codeforces_handle)
            obj.save()

            from django.template.loader import render_to_string
            from django.utils.html import strip_tags
            
            datatuple = []
            mp = {
                'uid' : obj.uid,
                'domain': os.environ.get('ALLOWED_HOSTS').split(',')[1],
            }
            subject = "Moontasir's Blog"
            html_message = render_to_string('mail/emailVerification.html', mp)
            plain_message = strip_tags(html_message)
            from_email = 'Verify Email <' + str(os.environ.get('EMAIL_HOST_USER')) + '>'
            tple = (subject,plain_message,html_message,from_email,[email_address])
            datatuple.append(tple)
            
            send_mass_html_mail(datatuple)
            
            response = {
                'success': "We have sent a confirmation email. Please login to your email account to verify",
            }
            return JsonResponse(response)
        except Exception as e:
            response = {
                'msg': "Form data not valid, " + str(e),
            }
            return JsonResponse(response)

    context.update(SideBarWork())
    return render(request, 'codeforces/form.html' , context)


def confirmMail(request,uid):
    try :
        obj = Handle.objects.get(uid = uid)
        obj.isVerified = True
        obj.save()
        messages.success(request,'Your Email is verified')
    except :
        messages.error(request,'Invalid url')
    context = {}
    context.update(SideBarWork())
    return render(request,'blog/blogHome.html', context)


def unSubscribeCF(request, uid):
    try:
        handle = Handle.objects.get(uid = uid)
        handle.isActive = False
        handle.save()
        messages.success(request, 'Sorry to see you leave. To subscrive again you habe to refill the form from our website')
    except:
        messages.error(request, 'Invalid Url')
    context={}
    context.update(SideBarWork())
    return render(request , 'blog/blogHome.html' , context)

    pass

templates/codeforces/form.html
{% extends 'base.html' %}
{% load static %}
{% block title %} CF Rank Email Notification {% endblock%}
{% block css %}
<link rel="stylesheet" href="{% static 'css/style.css'%}" />

{% endblock css %}



{% block content %}

<div class="section-top-border">
    <h3 class="mb-30 title_color">Codeforces Rank Email Notifier</h3>
    <div class="row">
        <div class="col-lg-12">
            <blockquote class="generic-blockquote">
                “After every contest we will send an email about your countrywise rank, university rank and Global Rank.
                To get your rank in your email please fill up the following form.
                Remember that we will not sent any email if your email account is not verified. after filling up the
                form please check your email inbox to get a verify link”
            </blockquote>
        </div>
    </div>
</div>

<div class="mt-10">
    <input id="first_name" type="text" name="first_name" placeholder="First Name" onfocus="this.placeholder = ''"
        onblur="this.placeholder = 'First Name'" required class="single-input">
</div>
<div class="mt-10">
    <input id="last_name" type="text" name="last_name" placeholder="Last Name" onfocus="this.placeholder = ''"
        onblur="this.placeholder = 'Last Name'" required class="single-input">
</div>
<div class="mt-10">
    <input id="codeforces_handle" type="text" name="codeforces_handle" placeholder="Codeforces handle"
        onfocus="this.placeholder = ''" onblur="this.placeholder = 'Codeforces handle'" required class="single-input">
</div>
<div class="mt-10">
    <input id="email_address" type="email" name="EMAIL" placeholder="Email address (Verification Required)"
        onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email address (Verification Required)'" required
        class="single-input">
</div>
<div class="mt-10 text-left">
    <button onclick="cfInfoSubmit()" type="submit" value="submit" class="btn submit_btn">Submit Your Info</button>
</div>


{% endblock content %}


{% block js %}

<!-- Nav Design -->
{% if navText %}
<script type="text/javascript">
    navText = "{{navText}}";
    a = $(".nav-item");
    for (var i = 0; i < a.length; i++) {
        for (var j = 0; j < a[i].childNodes.length; j++) {
            if (a[i].childNodes[j].text) {
                if (a[i].childNodes[j].text == navText)
                    a[i].classList.add("active");
            }
        }
    }
</script>
{% endif %}

<!-- form submit -->
<script type="text/javascript">
    const cfInfoSubmit = () => {
        $.ajax({
            type: "POST",
            url: "{% url 'codeforces:cfForm' %}",
            data: {
                first_name: String($('#first_name').val()),
                last_name: String($('#last_name').val()),
                codeforces_handle: String($('#codeforces_handle').val()),
                email_address: String($('#email_address').val()),
                csrfmiddlewaretoken: '{{ csrf_token }}',
                dataType: "json",
            },

            success: function (data) {
                if (data.msg) {
                    alert(data.msg);
                }
                else {
                    if (data.success) {

                        alert(data.success);
                        location.reload();
                    }
                }
            },

            failure: function (data) {
                alert('Something is wrong... Check your internet connection');
            }
        });
    }
</script>

{% endblock %}